# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RFID-Base
version:      0.003
version_from: lib/RFID/Reader.pm
installdirs:  site
requires:
    Carp:                          0
    constant:                      0
    Exporter:                      0
    Fcntl:                         0
    IO::Handle:                    0
    IO::Socket:                    0
    IO::Socket::INET:              0
    Scalar::Util:                  0
    Test::More:                    0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
